name: phishing-detection
channels:
  - conda-forge
  - defaults
dependencies:
 - python=3.8
 - wandb=0.12.16
 - pip=21.2.4
 - jupyter=4.6.3
 - ipykernel
 - pandas
 - promise
 - protobuf
 - psutil
 - pathtools